services:
  backend:
    build: ./backend
    restart: always
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    environment:
      - PORT=${BACK_PORT}
      - API_HOST=bank_api
      - API_PORT=${API_PORT}
      - SCORING_HOST=scoring
      - SCORING_PORT=${SCORING_PORT}
    stdin_open: true
    tty: true

  scoring:
    build: ./scoring
    restart: always
    ports:
      - ${SCORING_PORT}:${SCORING_PORT}
    environment:
      - PORT=${SCORING_PORT}
    stdin_open: true
    tty: true

  bank_api:
    build: ./bank_api
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
    stdin_open: true
    tty: true

#  frontend:
#    build: ./frontend
#    ports:
#      - 3000:3000
