services:
  backend:
    build: ./backend
    restart: always
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    environment:
      - BACK_PORT=${BACK_PORT}
    stdin_open: true
    tty: true
  scoring:
    build: ./scoring
    restart: always
    ports:
      - ${SCORING_PORT}:${SCORING_PORT}
    environment:
      - PORT=${SCORING_PORT}
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
