services:
  scoring:
    build: ./scoring
    restart: always
    ports:
      - ${SCORING_PORT}:${SCORING_PORT}
    environment:
      - PORT=${SCORING_PORT}
    stdin_open: true
    tty: true

  bank_api:
    build: ./bank_api
    restart: always
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - PORT=${API_PORT}
    stdin_open: true
    tty: true
  bot:
    build: ./chat_bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - API_ADDRESS=http://bank_api:${API_PORT}
  backend:
    build: ./backend
    restart: always
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    environment:
      - PORT=${BACK_PORT}
      - API_ADDRESS=http://bank_api:${API_PORT}
      - SCORING_ADDRESS=http://scoring:${SCORING_PORT}
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - 80:3000
